site_name: PMA.261 - Store Platform
site_description: Documentação do projeto desenvolvido na disciplina PMA.261
site_author: Thaís, Carol e Fernando

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.highlight

nav:
  - Home: index.md

  - Exercícios:
      - Product API: exercicios/product-api.md
      - Order API: exercicios/order-api.md
      - Exchange API: exercicios/exchange-api.md
      - Jenkins: exercicios/jenkins.md
      - Kubernetes: exercicios/k8s.md
      - Bottlenecks: exercicios/bottlenecks.md

  - Projeto:
      - Overview: projeto/overview.md
      - Arquitetura: projeto/arquitetura.md
      - CI/CD: projeto/ci-cd.md
      - Teste de Carga: projeto/teste-carga.md
      - Custos: projeto/custos.md
      - PaaS: projeto/paas.md
      - Vídeo: projeto/video.md

  - Membros:
      - Thaís Rocha Silveira: membros/thais.md
      - Carol: membros/carol.md
      - Fernando: membros/fernando.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search